name: drinkt_q
description: "WAH wah WAH."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # state manager?
  flutter_riverpod: ^2.6.1

  # dependencies from pub.dev:
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  animations: ^2.0.11
  logger: ^2.5.0
  easy_localization: ^3.0.7
  go_router: ^14.6.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  http: ^1.2.2
  form_validator: ^2.1.1
  mask_text_input_formatter: ^2.9.0
  flutter_launcher_icons: ^0.14.1
  socket_io_client: ^3.0.2
  dio: ^5.7.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.3.6
  bubble: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  country_flags: ^3.2.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.0.18
  flutter_slidable: ^3.1.2
  swipeable_tile: ^2.0.1
  popup_menu: ^2.1.0
  app_bar_with_search_switch: ^1.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:

# config for the flutter_launcher_icons
# for run:
# flutter pub run flutter_launcher_icons:generate
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_foreground_inset: 16
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_android: "#FFFFFF"
  background_color_ios: "#FFFFFF"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/translations/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_18pt-Black.ttf
          weight: 900


# easy_localization generate .g.dart file from build_runner
# for run:
# dart pub global activate rps
# rps gen_locale_keys
scripts:
  gen_locale_keys: flutter pub run easy_localization:generate -S assets/translations -f keys -O lib/core/translations
  # alternative
  # gen_locale_keys: dart run easy_localization:generate -S assets/translations -f keys -O lib/core/translations

  # old
  # gen_locale_keys: dart run easy_localization:generate -S assets/translations -f keys -O lib/core/translations

  # or run
  # flutter pub run easy_localization:generate -S assets/translations -f keys -O lib/core/translations


# rename
# app rename for the run:
# flutter pub global activate rename
# rename setAppName --targets ios,android --value "YourAppName"

